function writeNavbar() {
    document.write("<div class=\"container\">")
    document.write("<div class=\"navWrapper\">")
    document.write("<div class=\"leftHeader\">")
    document.write("<div class=\"navLink\">")
    document.write("<a href=\"HomePage.html\">Home</a>")
    document.write("</div>")
    document.write("<div class=\"navLink active-nav-link\">")
    document.write("<a href=\"About.html\" id=\"about\">About Me</a>")
    document.write("</div>")
    document.write("</div>")
    document.write("<div class=\"rightHeader\">")
    document.write("<div class=\"navLink\">")
    document.write("<a href=\"myInfo.html\">William Phenicie</a>")
    document.write("</div>")
    document.write("</div>")
    document.write("</div>")
    document.write("</div>")
}

writeNavbar()